#:kivy 2.3.1
#:include styles.kv

<RunnerGui>:    
    BoxLayout: 
        orientation: 'vertical'
        padding: 3
        spacing: 3
        
        BoxLayout:
            orientation: 'horizontal'
            spacing: 3
            BasePanel:
            BasePanel:
                size_hint_x: None
                width: 200
        BasePanel:
            size_hint_y: None
            height: 200