#:kivy 2.2.1
#:include common.kv

<PromptsItem@Label>
    size_hint: None, None
    size: self.texture_size

<PromptsPanel@BoxLayout>
    orientation: 'horizontal'
    prompt_list: prompt_list
    ScrollView:
        StackLayout:
            spacing: 5
            orientation: 'tb-lr'
            id: prompt_list
    BoxLayout:
        size_hint_x: None
        width: 160
        orientation: 'vertical'
        Button:
            text: 'Load'


